site_name: Indian Name Generator
site_description: A Python package to generate Indian names
site_author: Ankit Kumar
repo_url: https://github.com/ankitprasad81/indian-name-generator

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Python API: usage/python-api.md
    - Command Line: usage/command-line.md
  - License: license.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

plugins:
  - search
